name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *' # every 24 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update TryHackMe badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "epsilon003"
          image_path: "./assets/thm_propic.png"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
